repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  - name: javahttptest
    namespace: monitoring
    chart: java-http/helm-chart

  - name: javagrpctest
    namespace: monitoring
    chart: java-grpc/helm-chart

  - name: gohttptest
    namespace: monitoring
    chart: go-http/helm-chart

  - name: gogrpctest
    namespace: monitoring
    chart: go-grpc/helm-chart

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    hooks:
    - events: ["postupgrade", "postinstall", "postsync"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "./metallb.yaml"]
