{
 "title": "Termômetros",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "tabelas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "javahttp",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "request_timer_seconds_sum{service=\"javahttptest-helm-chart\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "javagrpc",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "gohttp",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "request_timer_sum{service=\"gohttptest-helm-chart\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "gogrpc",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "request_timer_sum{service=\"gogrpctest-helm-chart\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "confidence interval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "candlestick",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
       "legendFormat": "x javahttp"
      },
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
       "legendFormat": "x javagrpc"
      },
      {
       "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
       "legendFormat": "x gohttp"
      },
      {
       "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
       "legendFormat": "x gogrpc"
      },
      {
       "expr": "stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"}) / (sqrt(count(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})))",
       "legendFormat": "erro javahttp"
      },
      {
       "expr": "stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"}) / (sqrt(count(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})))",
       "legendFormat": "erro javagrpc"
      },
      {
       "expr": "stddev(request_timer_sum{service=\"gohttptest-helm-chart\"}) / (sqrt(count(request_timer_sum{service=\"gohttptest-helm-chart\"})))",
       "legendFormat": "erro gohttp"
      },
      {
       "expr": "stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"}) / (sqrt(count(request_timer_sum{service=\"gogrpctest-helm-chart\"})))",
       "legendFormat": "erro gogrpc"
      },
      { "expression": "$A + 1.96 * $E", "type": "math" },
      { "expression": "$A - 1.96 * $E", "type": "math" },
      { "expression": "$B + 1.96 * $F", "type": "math" },
      { "expression": "$B - 1.96 * $F", "type": "math" },
      { "expression": "$C + 1.96 * $G", "type": "math" },
      { "expression": "$C - 1.96 * $G", "type": "math" },
      { "expression": "$D + 1.96 * $H", "type": "math" },
      { "expression": "$D - 1.96 * $H", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "t test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "t-test (java-http x java-grpc)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
       "legendFormat": "x-java-http"
      },
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
       "legendFormat": "x-java-grpc"
      },
      {
       "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})) + (stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "t-test (go-http x go-grpc)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
       "legendFormat": "x-go-http"
      },
      {
       "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
       "legendFormat": "x-go-grpc"
      },
      {
       "expr": "sqrt((stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})/count(request_timer_sum{service=\"gohttptest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})/count(request_timer_sum{service=\"gogrpctest-helm-chart\"})) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "t-test (java-http x go-http)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
       "legendFormat": "x-java-http"
      },
      {
       "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
       "legendFormat": "x-go-http"
      },
      {
       "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})/count(request_timer_sum{service=\"gohttptest-helm-chart\"})) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "t-test (java-grpc x go-grpc)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
       "legendFormat": "x-java-grpc"
      },
      {
       "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
       "legendFormat": "x-go-grpc"
      },
      {
       "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})/count(request_timer_sum{service=\"gogrpctest-helm-chart\"})) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "t-test (java-http x go-grpc)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
       "legendFormat": "x-java-http"
      },
      {
       "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
       "legendFormat": "x-go-grpc"
      },
      {
       "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})/count(request_timer_sum{service=\"gogrpctest-helm-chart\"})) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "t-test (java-grpc x go-http)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
       "legendFormat": "x-java-grpc"
      },
      {
       "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
       "legendFormat": "x-go-http"
      },
      {
       "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})/count(request_timer_sum{service=\"gohttptest-helm-chart\"})) )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Basic data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "java-http (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "java-grpc (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "java-http (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "java-grpc (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-http (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-grpc (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-http (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-grpc (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}