{
 "title": "Termômetros",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "t-test (java-http x java-grpc)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
     "legendFormat": "x-java-http"
    },
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
     "legendFormat": "x-java-grpc"
    },
    {
     "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})) + (stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "t-test (go-http x go-grpc)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
     "legendFormat": "x-go-http"
    },
    {
     "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
     "legendFormat": "x-go-grpc"
    },
    {
     "expr": "sqrt((stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})/count(request_timer_sum{service=\"gohttptest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})/count(request_timer_sum{service=\"gogrpctest-helm-chart\"})) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "t-test (java-http x go-http)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
     "legendFormat": "x-java-http"
    },
    {
     "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
     "legendFormat": "x-go-http"
    },
    {
     "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})/count(request_timer_sum{service=\"gohttptest-helm-chart\"})) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "t-test (java-grpc x go-grpc)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
     "legendFormat": "x-java-grpc"
    },
    {
     "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
     "legendFormat": "x-go-grpc"
    },
    {
     "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})/count(request_timer_sum{service=\"gogrpctest-helm-chart\"})) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "t-test (java-http x go-grpc)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
     "legendFormat": "x-java-http"
    },
    {
     "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
     "legendFormat": "x-go-grpc"
    },
    {
     "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})/count(request_timer_sum{service=\"gogrpctest-helm-chart\"})) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "t-test (java-grpc x go-http)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
     "legendFormat": "x-java-grpc"
    },
    {
     "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
     "legendFormat": "x-go-http"
    },
    {
     "expr": "sqrt((stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})/count(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})) + (stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})/count(request_timer_sum{service=\"gohttptest-helm-chart\"})) )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "java-http (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "java-grpc (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "java-http (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_seconds_sum{service=\"javahttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "java-grpc (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_seconds_sum{service=\"javagrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-http (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_sum{service=\"gohttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-grpc (média)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-http (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_sum{service=\"gohttptest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-grpc (desvio padrão)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(request_timer_sum{service=\"gogrpctest-helm-chart\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}