apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc
spec:
  selector:
    matchLabels:
      app: go-grpc
  template:
    metadata:
      labels:
        app: go-grpc
    spec:
      containers:
      - name: go-grpc
        image: luizdopc/go-grpc:v0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50001
