version: '3.3'

networks:
  aw-network:
   driver: bridge

volumes:
  prometheus_data:
   
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_grpc
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - aw-network
  java-http:
    image: luizdopc/java-grpc:v0.3
    container_name: java-grpc
    ports:
      - 8080:8080
      - 50051:50051
    networks:
      - aw-network
  grafana:
    image: grafana/grafana
    container_name: grafana_grpc
    ports:
      - 3000:3000
    networks:
      - aw-network